import Head from 'next/head'
import Accordion from '../components/organisms/Accordion'
import styles from '../styles/Home.module.css'
import TypingEffect from '../components/molecules/TypeEffect'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Steven Chafin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Steven Chafin
          </h1>
            <TypingEffect />
          <div className="justify-center self-center justify-self-center text-center mx-auto w-full">
            <Accordion />
          </div>
        </main>
     </div>
  )
}
