import Head from 'next/head'
import Accordion from '../components/organisms/Accordion'
import styles from '../styles/Home.module.css'
import TypingEffect from '../components/molecules/TypeEffect'
import projects from '../shared/projects.json'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <h1 className={styles.title}>
          Steven Chafin
        </h1>
          <TypingEffect />
        <div className="justify-center self-center justify-self-center text-center mx-auto w-full">
          <Accordion props={data} />
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
export async function getStaticProps() {
  const data = projects;
  return {
    props: {
      data
    }, // will be passed to the page component as props
  }
}